spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hosp-ms
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  compression:
    enabled: true
    mime-types: application/json